"""add conversation_id to chat_history

Revision ID: 0af6b876c297
Revises: 72ba5f938cbf
Create Date: 2026-08-26 14:11:30.446053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af6b876c297'
down_revision: Union[str, Sequence[str], None] = '72ba5f938cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_history', 'conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_column('chat_history', 'conversation_id')
    # ### end Alembic commands ###
