"""add token columns

Revision ID: 154d1238b937
Revises: 7d9b63c3e613
Create Date: 2026-08-25 14:28:09.744033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154d1238b937'
down_revision: Union[str, Sequence[str], None] = '7d9b63c3e613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('success', sa.Boolean(), nullable=False,server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'success')
    op.drop_column('chat_history', 'output_tokens')
    op.drop_column('chat_history', 'input_tokens')
    # ### end Alembic commands ###
