"""add ai_prompt_runs table

Revision ID: 8c9e43daa47c
Revises: 9a012048a79f
Create Date: 2026-08-27 15:55:19.984291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9e43daa47c'
down_revision: Union[str, Sequence[str], None] = '9a012048a79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompt_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('selected_provider', sa.String(length=100), nullable=False),
    sa.Column('selected_model', sa.String(length=100), nullable=True),
    sa.Column('strategy_md', sa.Text(), nullable=True),
    sa.Column('final_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_prompt_runs')
    # ### end Alembic commands ###
